services:
  - type: web_service
    name: flashcart-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: JWT_SECRET
        value: "<set-in-render>"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://flashcart-frontend.onrender.com"
    branch: main
    region: oregon
    autoDeploy: true

  - type: static_site
    name: flashcart-frontend
    staticPublishPath: frontend/public
    branch: main
    region: oregon
    autoDeploy: true
